In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import shapiro
from scipy.stats import kstest
df = pd.read_csv(r'../data/urozhai_data_Cleaned.csv')

df

,Год,Регион,Культура,Урожайность (т/га),Площадь (га),Общее производство (т),Осадки (мм),Температура (°C),Удобрения (кг/га)
0,2010,Сибирь,Пшеница,3.185431,5860,18666.622934,476.867307,20.593820,139.527524
1,2010,Сибирь,Ячмень,3.001689,21023,63104.502594,476.867307,6.128232,158.299816
2,2010,Сибирь,Кукуруза,4.278667,24769,105978.297804,514.853859,13.638900,93.684371
3,2010,Сибирь,Картофель,3.148628,5189,16338.232222,254.363861,17.367720,107.369299
4,2010,Сибирь,Подсолнечник,4.561384,19502,88956.109279,476.867307,23.844035,134.493233
...,...,...,...,...,...,...,...,...,...
345,2023,Дальний Восток,Пшеница,4.234885,25360,107396.672191,281.960542,18.032795,160.789619
346,2023,Дальний Восток,Ячмень,4.709431,13547,63798.661415,251.204802,5.860139,150.029999
347,2023,Дальний Восток,Кукуруза,3.707488,49617,96723.414289,208.816033,12.581881,100.601832
348,2023,Дальний Восток,Картофель,3.717891,39926,148440.501294,398.145668,15.281885,90.001279
349,2023,Дальний Восток,Подсолнечник,3.289414,49864,164023.345089,387.118315,20.479828,165.938222